# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Develop CI

on:
  push:
    branches: [ "feature/**", "release-**" ]

jobs:
  develop-ci:
    runs-on: ubuntu-latest
    env:
      working-directory: ./chapter2/ticketing
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant Authority
      run: chmod +x ./gradlew
      working-directory: ${{ env.working-directory }}

    - name: Test with Gradle
      run: ./gradlew test
      working-directory: ${{ env.working-directory }}

    - name: Build with Gradle
      run: ./gradlew build -x test
      working-directory: ${{ env.working-directory }}

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/develop-ticketing .
      working-directory: ${{ env.working-directory }}

    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/develop-ticketing
    #  env:
    #    USERNAME: ${{ github.actor }}
    #    TOKEN: ${{ secrets.GITHUB_TOKEN }}
